### PR TITLE
Fix build process

### PR DESCRIPTION
**Pull request by humrochagf**
When installing as a requirement at packages.json, it was not able to fetch the src and build the dist folder properly.

So this PR fixes the automatic build process that runs at the instalation of the package

### CODE REVIEW

**Comment by wbhob** [comment]
I already fixed this, just waiting for @scott-wyatt to publish. As a general rule, don't publish source files to NPM, it's bad practice.

**Comment by humrochagf** [comment]
get it, thx.

and just to better understanding of the process, how does the npm will generate the dist folder since it does not get the source and the dist isn't pre built at the repo?

**Comment by wbhob** [comment]
We build it with the `prepublish` npm command.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com
Twitter/Instagram/Facebook: @getcanal

**Comment by wbhob** [comment]
Why was this merged? I closed it because I already fixed it @scott-wyatt

**Comment by wbhob** [comment]
Shoot did I forget to close it?

**Pull request merged**
