### PR TITLE
Test env

### PR DESCRIPTION
**Pull request by scott-wyatt**
- AOT/SSR support
- Testing Suite with AOT/SSR
- ng-packagr library bundler
- Testing Environment App

### CODE REVIEW

**Comment by scott-wyatt** [comment]
Fixes #34 and implements #37

**Comment by wbhob** [comment]
holy s**t why are there so many changed files? were dist files commited?

**Comment by wbhob** [comment]
ok i see now. i'm going to need a little while to parse this, probably just a couple of days

**Comment by scott-wyatt** [comment]
Lol, there’s a lot because I’ve added a test environment app. When you do the ng-packagr build it just packages up the library and leaves out the rest. We’ve been doing all our angular libraries this way so we can test it against our stacks. Welcome to angular in 2018.

**Comment by wbhob** [comment]
Alright looks like everything works well. Magnificent PR! Ready to merge.

**Review by wbhob — APPROVED** [review]

**Pull request merged**
