### PR TITLE
Possibly merge these changes into the package?

### PR DESCRIPTION
**Pull request by wbhob**
It'd be great if we could have one central repo with this functionality. Would you consider updating your code to match the current master so we can merge this functionality in?

### CODE REVIEW

**Comment by scott-wyatt** [comment]
Lol, at least keep me as a contributor in the package.json and sure!

**Comment by wbhob** [comment]
hehe lol @adamkundrat would you be ok with this?

**Comment by wbhob** [comment]
I actually have no idea why I am listed as the author in package.json, that isn't even my fork!

**Comment by scott-wyatt** [comment]
Closing for now, this will need to be refactored to work with the current lib.

**Pull request closed without merging**
