### PR TITLE
Attempt to fix #74

### LINKED ISSUE #74: Function calls are not supported in decorators but 'IntercomModule' was called. - Regression in beta.6
_Originally posted by @chrishawn in https://github.com/CaliStyle/ng-intercom/issue_comments#issuecomment-430313444_

### PR DESCRIPTION
**Pull request by wbhob**
Summary of changes: 

Intended/example use case: 

Checklist:
- [ ] `npm run build` runs without error
- [ ] `ng serve` spawns app, Intercom messenger is visible and interactive, and there are no errors in the console

Closes issue: #

### CODE REVIEW

**Comment by danielnswz** [comment]
Hello @wbhob, I just did pull to try your branch and returns 

ERROR in src/app/app.module.ts(21,30): error TS2307: Cannot find module 'ng-intercom'.

any help to integrate would be nice.

**Comment by wbhob** [comment]
1) clone this repo
1a) checkout into the `wilson-74` branch
2) run `npm run build:dist`
3) from your project directory, run `npm install <dir>`, where dir is the exact location of the dist folder of the repo. So, if your current working directory is `~/myApp`, and ng-intercom is in `~/ng-intercom`, run `npm install ../ng-intercom/dist` and that will resolve the package correctly.
4) run your app/run an AoT build and see if the error persists

Thanks for your help with testing!

**Comment by danielnswz** [comment]
Hey hey, it's me again :)

here's the result:

WARNING in ../ng-intercom/node_modules/@angular/core/fesm5/core.js 15201:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ../ng-intercom/node_modules/@angular/core/fesm5/core.js 15213:15-102
Critical dependency: the request of a dependency is an expression


I followed the procedure, built ng-intercom, then installed in my project and when I run it, that's console result, and chrome says aditional info: 

ERROR Error: StaticInjectorError(AppModule)[Intercom -> InjectionToken Platform ID]: 
  StaticInjectorError(Platform: core)[Intercom -> InjectionToken Platform ID]: 
    NullInjectorError: No provider for InjectionToken Platform ID!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get

Thanks for the help.

**Comment by vdzundza** [comment]
Hi
The 3rd step is failing for me

```
vdzundza at Viktors-MacBook-Pro in ~/p/front_web-client (fix_intercom|✚2)
⋊  npm install ./../ng-intercom/dist                                                                             Tue Oct 30 18:15:22 2018
npm WARN checkPermissions Missing write access to /Users/vdzundza/projects/ng-intercom/dist/node_modules/tslib
npm WARN checkPermissions Missing write access to /Users/vdzundza/projects/ng-intercom/dist/node_modules
npm WARN @ngx-prism/core@2.0.1 requires a peer of @types/prismjs@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/cdk@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/common@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/core@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/animations@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/platform-browser@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@6.1.10 requires a peer of @angular/platform-browser@6.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-fullstory@1.0.7 requires a peer of @angular/core@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-fullstory@1.0.7 requires a peer of @angular/router@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-fullstory@1.0.7 requires a peer of @angular/common@^6.1.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/vdzundza/projects/ng-intercom/dist/node_modules/tslib
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/vdzundza/projects/ng-intercom/dist/node_modules/tslib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vdzundza/.npm/_logs/2018-10-30T16_15_38_150Z-debug.log
vdzundza at Viktors-MacBook-Pro in ~/p/front_web-client (fix_intercom|✚2)
```

**Comment by wbhob** [comment]
@vdzundza you need to npm install, and/or npm install tslib

@danielnswz are you importing browser module or something? You have to start your app from a platform

**Comment by LiamLB** [comment]
Hi,

I managed to build this PR. Additionally, I followed your provided steps and was able to install directly into my project.  Non-AoT builds and ng serve were both successful. However, I'm still encountering the issue outlined in #74. 

I did browse source and try a few things that were mentioned from similar issues on other projects to no avail. Any direction I could look into in particular to assist you in diagnosing/fixing this?

**Comment by wbhob** [comment]
@LiamEntrostat  Honestly, I don't know what this problem is and I haven't been able to resolve it. 

If you find it, and manage to get it to work, I'd be thrilled to merge your PR. Thanks for your help!

**Pull request merged**
